export const FAQ_MODE = {
  DEFAULT: 'DEFAULT',
  PRODUCT_GUIDE: 'PRODUCT_GUIDE',
  ORDER_PAY: 'ORDER_PAY',
  DELIVERY: 'DELIVERY',
  EXCHANGE_RETURN: 'EXCHANGE_RETURN',
  PRODUCT_WARRANTY: 'PRODUCT_WARRANTY',
  ETC: 'ETC',
};
