name: CI - 빌드

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 버전 설정
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 소셜 로그인 URL 생성
        run: |
          echo "const SOCIAL_LOGIN_URL = {" > src/global/url.js
          echo "  KAKAO: '${{ secrets.KAKAO }}'," >> src/global/url.js
          echo "  NAVER: '${{ secrets.NAVER }}'," >> src/global/url.js
          echo "  GOOGLE: '${{ secrets.GOOGLE }}'," >> src/global/url.js
          echo "  FACEBOOK: '${{ secrets.FACEBOOK }}'," >> src/global/url.js
          echo "};" >> src/global/url.js
          echo "export { SOCIAL_LOGIN_URL };" >> src/global/url.js

      - name: 의존성 설치
        run: npm install

      - name: 빌드
        run: CI=false npm run build
