name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create src/global/url.js
        run: |
          echo "const SOCIAL_LOGIN_URL = {" > src/global/url.js
          echo "  KAKAO: '${{ secrets.KAKAO }}'," >> src/global/url.js
          echo "  NAVER: '${{ secrets.NAVER }}'," >> src/global/url.js
          echo "  GOOGLE: '${{ secrets.GOOGLE }}'," >> src/global/url.js
          echo "  FACEBOOK: '${{ secrets.FACEBOOK }}'," >> src/global/url.js
          echo "};" >> src/global/url.js
          echo "export { SOCIAL_LOGIN_URL };" >> src/global/url.js
          

      - name: Build Docker image
        run: |
          docker build -t my-frontend-app -f multistage.Dockerfile .
          docker tag my-frontend-app ghcr.io/liberty52/liberty52-front-end:dev-v${{ github.sha }}
        working-directory: ./

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GTOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/liberty52/liberty52-front-end:dev-v${{ github.sha }}