name: Build and Push Docker Image

on:
  push:
    branches:
      - ci/docker-ci-pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Set SOCIAL_LOGIN_URL secret
        run: |
          echo "SOCIAL_LOGIN_URL={\"KAKAO\":\"${{ secrets.KAKAO }}\",\"NAVER\":\"${{ secrets.NAVER }}\",\"GOOGLE\":\"${{ secrets.GOOGLE }}\",\"FACEBOOK\":\"${{ secrets.FACEBOOK }}\"}" > src/global/url.js

      - name: Build Docker image
        run: |
          docker build -t my-frontend-app .
          docker tag my-frontend-app ghcr.io/liberty52/liberty52-front-end:${{ github.sha }}
        working-directory: ./multistage.Dockerfile

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/liberty52/liberty52-front-end:${{ github.sha }}
