name: Build and Push Docker Image

on:
  push:
    branches:
      - ci/docker-ci-pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set SOCIAL_LOGIN_URL secret
        run: |
          echo "SOCIAL_LOGIN_URL={\"KAKAO\":\"${{ secrets.KAKAO }}\",\"NAVER\":\"${{ secrets.NAVER }}\",\"GOOGLE\":\"${{ secrets.GOOGLE }}\",\"FACEBOOK\":\"${{ secrets.FACEBOOK }}\"}" > src/global/url.js

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build -t ghcr.io/liberty52/liberty52-front-end:dev-v${{ github.sha }} \
            --file Dockerfile \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${{ github.sha }} \
            --build-arg VERSION=1.0 \
            .

      - name: Login to GHCR
        run: echo ${{ secrets.GTOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/liberty52/liberty52-front-end:dev-v${{ github.sha }}
